import type { AppState } from "@/types";
export const trackerHeaders = [
  "Applicant ID",
  "Applicant Name",
  "Email",
  "Position",
  "Location",
  "Hiring Need",
  "Urgency",
  "Application Date",
  "Current Stage",
  "Application Status",
  "Screening Result",
  "Initial Interview Date",
  "Initial Interview Status",
  "Final Interview Date",
  "Final Interview Status",
  "Requirements Status",
  "Onboarding Status",
  "Hired Date",
  "Employment Status",
  "Withdrawal Reason",
  "Rejection Reason",
  "HR Notes",
  "Last Updated",
  "Assigned HR User",
];
export function trackerRows(state: AppState) {
  return state.applications.map((a) => {
    const need = state.hiringNeeds.find((n) => n.id === a.hiringNeedId),
      initial = a.interviews.find((i) => i.stage === "Initial Interview"),
      final = a.interviews.find((i) => i.stage === "Final Interview");
    return [
      a.id,
      a.applicant.name,
      a.applicant.email,
      a.position,
      a.location,
      need ? `${need.position} · ${need.location}` : "",
      need?.urgency || "",
      a.appliedAt,
      a.stage,
      a.status,
      a.screening.outcome,
      initial?.scheduledAt || "",
      initial?.status || "",
      final?.scheduledAt || "",
      final?.status || "",
      `${a.requirements.filter((r) => r.status === "Complete").length}/${a.requirements.length} complete`,
      a.onboardingStatus,
      a.hiredAt || "",
      a.employment?.status || "",
      a.withdrawalReason || "",
      a.rejectionReason || "",
      a.notes.join("\n"),
      a.lastActivity,
      a.assignedTo || "",
    ];
  });
}
